name = "Smc Creationista"
author = "nuark"
version = "1.0.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ec0ce3ff468e894cb44fbfe02c2bc78675c1568e9047aa660919f5d4d01bfa5"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"
